const data = {
  "data": {
    "backup_code_enabled": false,
    "banned": false,
    "birthday": "",
    "create_organization_enabled": true,
    "created_at": 1694583139909,
    "delete_self_enabled": true,
    "email_addresses": [
      {
        "email_address": "",
        "id": "idn_hash",
        "linked_to": [
          {
            "id": "idn_hash",
            "type": "oauth_google",
          },
        ],
        "object": "email_address",
        "reserved": false,
        "verification": {
          "attempts": null,
          "expire_at": null,
          "status": "verified",
          "strategy": "from_oauth_google",
        },
      },
    ],
    "external_accounts": [
      {
        "approved_scopes": "",
        "email_address": "",
        "family_name": "",
        "given_name": "",
        "google_id": "104502911807642723965",
        "id": "idn_hash",
        "label": null,
        "object": "google_account",
        "picture":
          "https://lh3.googleusercontent.com/a/ACg8ocJzn19QyKCnDZqfgIzEMD9SXy1NsoiyyMVCNmLSfl3FmA=s1000-c",
        "public_metadata": {},
        "username": null,
        "verification": {
          "attempts": null,
          "expire_at": 1694583735708,
          "status": "verified",
          "strategy": "oauth_google",
        },
      },
    ],
    "external_id": null,
    "first_name": "",
    "gender": "",
    "has_image": true,
    "id": "user_hash",
    "image_url": "",
    "last_name": null,
    "last_sign_in_at": null,
    "object": "user",
    "password_enabled": false,
    "phone_numbers": [],
    "primary_email_address_id": "idn_hash",
    "primary_phone_number_id": null,
    "primary_web3_wallet_id": null,
    "private_metadata": {},
    "profile_image_url": "",
    "public_metadata": {},
    "saml_accounts": [],
    "totp_enabled": false,
    "two_factor_enabled": false,
    "unsafe_metadata": {},
    "updated_at": 1694583139948,
    "username": null,
    "web3_wallets": [],
  },
  "object": "event",
  "type": "user.created",
};

export default data;
